### ISSUE TITLE
modular-backbone

### ISSUE THREAD

**Issue by kevsmt** [thomasdavis/backbonetutorials#15]
Hi Thom, 

I read your post and its great :) i did this one before but i didnt tried to continue because i dont know if i am in the right direction.  Do you have a solution for modules? which it has its own router, models, collection, etc?

like:

```
/modules/laptops
/modules/laptops/router.js
/modules/laptops/models/model.js <-- laptop models [ ibm, dell, sony, etc... ]
/modules/laptops/templates/model_lists.html
```

   ...
   ...

Thanks

Kevin

**Comment by thomasdavis** [comment]
Hi Kevin,
             this issue has been bought up a few times now so I will get back to you with a solid answer.

I believe their will be a mixture of "modules" and the way I implemented the file structure.

**Comment by kevsmt** [comment]
Thanks Thom

**Comment by kevsmt** [comment]
Hello Thomas, 

I tried to create a modular backbone, I haven't add models/controllers but it has views, so anyway here's the downloadable app: http://dl.dropbox.com/u/13224004/modular.zip, drop in to your localhost web root, and http://localhost/modular/app/

Tell me what you think.

Cheers!

Kevin

**Comment by thomasdavis** [comment]
Hey,
      awesome work so far.

Some points from my look over the code.
- I would prefer templates are abstracted out of the Javascript src folder so it is simpler for designers to get in to the html and change things when they need such as adding classes etc
- I wouldn't really include such a direct UI manipulation in the router.js
- Probably a good step forwards is starting to make sure nothing is global, therefore wrapping jquery and the rest so that they can be properly included as dependencies.  

Great initiative, will have another look at it tonight.

**Comment by kevsmt** [comment]
Hi Thomas, i updated it: http://dl.dropbox.com/u/13224004/modular-js.zip

Also, i was thinking about using onilabs.com/apollo for this.. any thoughts if that would be a good alternative? i tried it though, but i have a problem in backbone, which if it sees that it has a require, it automatically executes require('underscore');

**Comment by kevsmt** [comment]
Also, Thomas, I dont know how i find it but, its a very good start learning about http://angularjs.org/#/

**Comment by thomasdavis** [comment]
I personally don't like reactive documents such as angularjs

**Comment by thomasdavis** [comment]
In regards to the Backbone using require this is a known issue and is being looked at here
https://github.com/documentcloud/backbone/pull/688
